### ISSUE TITLE
can't consume a file message

### ISSUE THREAD

**Issue by chocronr** [gdaws/node-stomp#68] opened 2017-10-25 15:41 UTC
I am trying to consume a message contaning a file. When I consume the message, and save the resulting file, it is different from the initial file that I uploaded. What is my problem?

Here is the add message function:
async addFileMessage(filePath, queueName, id, type) {
        stompit.connect(this.connectParams, function (error, client) {

            if (error) {
                console.log('Unable to connect: ' + error.message);
                return;
            }

            let fileStat = fs.statSync(filePath);
            let contentLength = fileStat.size;
            console.log(contentLength);

            let sendParams = {
                'destination': '/queue/' + queueName,
                'content-type': 'application/octet-stream',
                'content-length': contentLength
            };

            if (id) {
                sendParams['correlation-id'] = id;
            }
            if (type) {
                sendParams['type'] = type;
            }

            let frame = client.send(sendParams);
            let file = fs.createReadStream(filePath);
            file.pipe(frame);

            frame.on('finish', function () {

                client.disconnect(function (error) {
                    if (error) {
                        console.log('Error while disconnecting: ' + error.message);
                        return;
                    }
                    console.log('Sent file');
                });

            });

        }.bind(this));

    }

And here is the consume function:
`    subscribe(queueName, callback) {
        stompit.connect(this.connectParams, function (error, client) {

            if (error) {
                console.log('Unable to connect: ' + error.message);
                callback(error, null);
            }

            let subscribeParams = {
                'destination': '/queue/' + queueName,
                'ack': 'client-individual'
            };

            client.subscribe(subscribeParams, function (error, message) {

                let correlationId = message['headers']['correlation-id'];
                let type = message['headers']['type'];

                let body = "";

                let read = function () {
                    let chunk;
                    while (null !== (chunk = message.read())) {
                        body += chunk;
                    }
                };

                message.on('readable', read);

                message.on('end', function () {
                    let obj = {'message': body, 'id': correlationId, 'type': type};
                    callback(null, obj);
                    client.ack(message);
                });

            });
        });`

**Comment by gdaws** [comment] 2017-11-10 00:22
I tested your code by transferring a PNG file and found that the consumer output corrupted data. The problem is the consumer is reading chunks and appending the data to a string and the string operation is performing some kind of character decoding.

The solution is to store the chunk data in a Buffer object.

```js
let body = Buffer.from([]);

let read = function () {
    let chunk;
    while (null !== (chunk = message.read())) {
        body = Buffer.concat([body, chunk], body.length + chunk.length);
    }
};
```
Or you could avoid the hassle of writing your own read logic and pipe the message into file stream.

```js
message.pipe(file);
```

**Comment by chocronr** [comment] 2017-11-12 12:07
Many thanks!
Indeed, consuming the file into a string corrupted the data.
My solution was to mark in the message header if this is a file, and in this case, consume it using file stream:

`subscribe(queueName, callback) {
        stompit.connect(this.connectParams, function (error, client) {

            if (error) {
                console.log('Unable to connect: ' + error.message);
                callback(error, null);
            }

            let subscribeParams = {
                'destination': '/queue/' + queueName,
                'ack': 'client-individual'
            };

            client.subscribe(subscribeParams, function (error, message) {

                let correlationId = message['headers']['correlation-id'];
                let type = message['headers']['type'];
                let hash = message['headers']['hash'];
                let ws, body, filePath;

                if (type === "file") {
                    let id = uuidv1();
                    filePath = config.downloadPath + "/" + id;
                    ws = fs.createWriteStream(filePath);
                }
                else {
                    body = "";
                }

                let read = function () {
                    let chunk;
                    while (null !== (chunk = message.read())) {

                        if (type === "file") {
                            ws.write(chunk);
                        }
                        else {
                            body += chunk;
                        }
                    }
                };

                message.on('readable', read);

                message.on('end', function () {
                    let obj = {'message': body, 'id': correlationId, 'type': type};
                    client.ack(message);
                    if (type !== "file") {
                        callback(null, obj);
                    }
                    else {
                        ws.end();
                        ws.on('finish', function () {
                            let obj = {'message': filePath, 'id': correlationId, 'type': type, 'hash': hash};
                            callback(null, obj);
                        })
                    }
                });

            });
        });
    }`

**Closed** 2017-11-12 12:10 UTC
