### ISSUE TITLE
Recursive process.nextTick detected warning

### ISSUE THREAD

**Issue by garrows** [gdaws/node-stomp#29] opened 2015-08-24 12:53 UTC
Hey,
I'm getting node spit this out when under a bit of load
`(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.`

I'm running `v0.10.38`

**Comment by gdaws** [comment] 2015-08-24 22:10
This issue has been reported before (issue #15) and a workaround was released in stompit v0.21.

The warning is caused by a flaw in node's stream implementation. This type of detection and warning was removed from node in v0.11.10.

If you're unable to upgrade node then you can suppress the warning by increasing the value of process.maxTickDepth variable.

**Comment by garrows** [comment] 2015-08-24 22:16
Thanks for the fast reply. We are stuck on 0.10 for now so I'll use the
work around. Does this affect 0.12 or io.js?

**Comment by gdaws** [comment] 2015-08-24 22:28
Neither are affected. From 0.11.10 onwards, node and io.js allow nextTick infinite recursion. The test I used to reproduce the problem worked without issue in v0.12 and io.js v1.

**Comment by garrows** [comment] 2015-08-24 22:31
Thanks :)

**Comment by garrows** [comment] 2015-08-24 22:40
Does this mean while a message is in transit (between client and server), process.nextTick loop will block any other operations on the node server (e.g. express won't process other connection requests)??

**Comment by gdaws** [comment] 2015-08-26 00:55
No, the node server won't be blocked by stompit reading a message.

A limited amount of nextTick recursion occurs in stompit when for example a large chunk of data, containing possibly hundreds of messages, is read on the socket. All the messages can be read and processed immediately in a nextTick loop if there's no external I/O requested or pauses in between by the subscriber. If enough messages are processed at once it triggers the nextTick recursion warning. No blocking occurs, the nextTick loop exits and control returns to the event loop when there's nothing left to read or when reading pauses on the socket. There's no blocking during reading.

**Comment by garrows** [comment] 2015-08-26 08:09
Thanks for the into

**Comment by garrows** [comment] 2015-08-26 08:09
*info

**Closed** 2015-08-26 08:08 UTC
